### ISSUE TITLE
Add documentation of query parameters

### ISSUE THREAD

**Issue by kingjon3377** [utopia-airlines/UtopiaSearchService#15]
If this were a more traditional REST API, I would be able to figure out how to interact with this by reading the route-creation lines in the controller code, but in this service there's only one route, for `/`. So please document what query parameters are recognized, and how to use them; `README.md` would be a good place for this, but a comment above the route in question would also work.

**Comment by STOzaki** [comment]
Yes, I have added each of the query parameters that the client or API can pass, along with description of each of them (#16)
